import 'dart:core';
import 'package:visualhdl_dart/src/variable.dart';

class Chip {
  Chip({
    required this.name,
    required this.input,
    required this.output,
    required this.parts,
  });

  String name;
  VariableTable input;
  VariableTable output;
  List<Chip> parts;

  Chip copyWith({
    String? name,
    VariableTable? input,
    VariableTable? output,
    List<Chip>? parts,
  }) {
    return Chip(
      name: name ?? this.name,
      input: input ?? this.input,
      output: output ?? this.output,
      parts: parts ?? this.parts,
    );
  }

  String generateHDLPart() {
    String variableLine = '';
    input.forEach((k, v) {
      String key = k.bus == null ? k.name : k.toString();
      variableLine += '$key=$v,';
    });
    output.forEach((k, v) {
      String key = k.bus == null ? k.name : k.toString();
      variableLine += '$key=$v';

      if (k != output.keys.last) {
        variableLine += ',';
      }
    });

    variableLine = variableLine.replaceAll(RegExp(r','), ', ');

    String finalLine = '$name ($variableLine);';

    return finalLine;
  }

  String generateHDLChip() {
    Set<String> inputVariables =
        input.keys.map((v) => v.getSizeString()).toSet();
    Set<String> outputVariables =
        output.keys.map((v) => v.getSizeString()).toSet();

    String partsString = '';
    for (final part in parts) {
      partsString += part.generateHDLPart();
      if (partsString.isNotEmpty && parts.last != part) {
        partsString += '\n      ';
      }
    }

    String hdlChip = '''
// Generated by visualhdl_dart.
// Timestamp: UTC ${DateTime.timestamp()}

CHIP $name {
   IN ${inputVariables.join(', ')};
   OUT ${outputVariables.join(', ')};

   PARTS:
      $partsString
}''';

    return hdlChip;
  }
}
