import 'dart:core';
import 'package:visualhdl_dart/src/variable.dart';

class ChipBuilder {
  String? _name;
  VariableTable? _input;
  VariableTable? _output;
  List<Chip>? _parts;

  String get name => _name ?? '';
  VariableTable get input => _input ?? VariableTable([]);
  VariableTable get output => _output ?? VariableTable([]);
  List<Chip> get parts => _parts ?? [];

  set name(String newValue) => _name = newValue;
  set input(VariableTable newValue) => _input = newValue;
  set output(VariableTable newValue) => _output = newValue;
  set parts(List<Chip> newValue) => _parts = newValue;

  Chip build() {
    assert(_name != null);
    assert(_input != null);
    assert(_output != null);
    assert(_parts != null);

    return Chip(
      name: _name!,
      input: _input!,
      output: _output!,
      parts: _parts!,
    );
  }

  @override
  bool operator ==(Object other) {
    return other is ChipBuilder &&
        name == other.name &&
        input == other.input &&
        output == other.output &&
        parts == other.parts;
  }

  @override
  int get hashCode => Object.hash(name, input, output, parts);
}

class Chip {
  Chip({
    required this.name,
    required this.input,
    required this.output,
    required this.parts,
  });

  String name;
  VariableTable input;
  VariableTable output;
  List<Chip> parts;

  Chip copyWith({
    String? name,
    VariableTable? input,
    VariableTable? output,
    List<Chip>? parts,
  }) {
    return Chip(
      name: name ?? this.name,
      input: input ?? this.input,
      output: output ?? this.output,
      parts: parts ?? this.parts,
    );
  }

  @override
  bool operator ==(Object other) {
    return other is Chip &&
        name == other.name &&
        input == other.input &&
        output == other.output &&
        parts == other.parts;
  }

  @override
  int get hashCode => Object.hash(name, input, output, parts);

  String generateHDLPart() {
    String variableLine = '';
    input.forEach((k, v) {
      String key = k.bus == null ? k.name : k.toString();
      String value = v.bus == null ? v.name : v.toString();
      variableLine += '$key=$value,';
    });
    output.forEach((k, v) {
      String key = k.bus == null ? k.name : k.toString();
      String value = v.bus == null ? v.name : v.toString();
      variableLine += '$key=$value';

      if (k != output.keys.last) {
        variableLine += ',';
      }
    });

    variableLine = variableLine.replaceAll(RegExp(r','), ', ');

    String finalLine = '$name ($variableLine);';

    return finalLine;
  }

  String generateHDLChip() {
    Set<String> inputVariables =
        input.keys.map((v) => v.getSizeString()).toSet();
    Set<String> outputVariables =
        output.keys.map((v) => v.getSizeString()).toSet();

    List<String> clockedInput =
        input.keys.where((v) => v.clocked).map((v) => v.name).toList();

    String partsString = '';
    for (final part in parts) {
      partsString += part.generateHDLPart();
      if (partsString.isNotEmpty && parts.last != part) {
        partsString += '\n      ';
      }
    }

    String hdlChip = '''
// Generated by visualhdl_dart.
// Timestamp: UTC ${DateTime.timestamp()}

CHIP $name {
   IN ${inputVariables.join(', ')};
   OUT ${outputVariables.join(', ')};

   PARTS:
      $partsString
   ${clockedInput.isNotEmpty ? '\nCLOCKED ${clockedInput.join(', ')};' : ''}
}''';

    return hdlChip;
  }
}
